name: Ready the code and deploy
on: [push, workflow_dispatch]
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying the codes
        uses: actions/checkout@v4

      - name: check code is copied or not
        run: ls -a

      - name: install dependencies
        run: npm install --frozen-lockfile

      - name: build code
        run: npm run build

  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: npm run test